/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TesteNative */

#ifndef _Included_TesteNative
#define _Included_TesteNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TesteNative
 * Method:    imprimir
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TesteNative_imprimir
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
